version: '3.8'

volumes:
  mysql-volume:

services:
  web:
    image: nginx:1.18
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html

  app:
    build: ./docker/php
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=yanbaru_db
      - DB_USERNAME=yanbaru_user
      - DB_PASSWORD=yanbaru_password

  db:
    image: mysql:latest
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: yanbaru_db
      MYSQL_USER: yanbaru_user
      MYSQL_PASSWORD: yanbaru_password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql